name: Feast apply

on: 
  push:
    branches:
      - main
    paths:
      - dev/**

jobs:
  feast_apply:
    runs-on: ubuntu-latest
    env:
      FEAST_VERSION: "0.11.0"
    steps:
      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
          architecture: x64
      # Run `feast apply`
      - uses: actions/checkout@v2
      - name: Install feast
        run: |
          pip install "feast=="$FEAST_VERSION
      - name: Run feast apply
        run: |
          cd dev
          feast apply
