name: Feast apply

on: 
  push:
    branches:
      - main
    paths:
      - dev/**

jobs:
  feast_apply:
    runs-on: ubuntu-latest
    env:
      FEAST_VERSION: "0.28.0"
    
    steps:
      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: x64
      
      - name: Set up AWS SDK
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      
      # Run `feast apply`
      - uses: actions/checkout@v2
      - name: Install feast
        run: |
          pip install "feast[aws]=="$FEAST_VERSION
      - name: Run feast apply
        run: |
          cd dev
          feast apply
