name: Feast plan (AWS)

on: 
  pull_request:
    branches:
      - main
    paths:
      - dev/**

jobs:
  feast_plan:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
          architecture: x64

      # Run `feast plan`
      - uses: actions/checkout@v2
      - name: Install feast
        run: pip install "feast[aws]"
      - name: Capture `feast plan` in a variable
        id: feast_plan
        env:
          FEAST_USAGE: "False"
          FEAST_FORCE_USAGE_UUID: None
          IS_TEST: "True"
        run: |
          echo 'FEAST_OUTPUT<<EOF' >> $GITHUB_OUTPUT
          cd dev; feast plan >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      # Post a comment on the PR with the results of `feast plan`
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        if: ${{ steps.feast_plan.outputs.FEAST_OUTPUT }}
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ${{ steps.feast_plan.outputs.FEAST_OUTPUT }}
  