name: Feast plan

on: 
  pull_request:
    branches:
      - main
    paths:
      - prd/**

jobs:
  feast_plan:
    runs-on: ubuntu-latest
    env:
      ENV_ZONE: prd
      FEAST_VERSION: "0.28.0"
    steps:
      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: x64

      - name: Set up AWS SDK
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GIT_PERSONAL_ACCESS_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: "Runing `feast plan` ($ENV_ZONE)"

      # Run `feast plan`
      - uses: actions/checkout@v2
      - name: Install feast
        run: pip install "feast[aws]=="$FEAST_VERSION
      - name: Capture `feast plan` in a variable
        id: feast_plan
        run: |
          echo 'FEAST_OUTPUT<<EOF' >> $GITHUB_OUTPUT
          cd $ENV_ZONE; feast plan >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      # Post a comment on the PR with the results of `feast plan`
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        if: ${{ steps.feast_plan.outputs.FEAST_OUTPUT }}
        with:
          token: ${{ secrets.GIT_PERSONAL_ACCESS_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ${{ steps.feast_plan.outputs.FEAST_OUTPUT }}
  