name: Feast apply (stg)

on: 
  push:
    branches:
      - main
    paths:
      - stg/**
      - .github/workflows/stg*

jobs:
  feast_apply:
    runs-on: ubuntu-latest
    env:
      FEAST_VERSION: "0.28.0"
      ENV_ZONE: stg
    
    steps:
      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: x64
      
      - name: Set up AWS SDK
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: private-gi-pa3-noti-test
          SLACK_USERNAME: feast-cicd
          SLACK_MSG_AUTHOR: aidenshin
          SLACK_TITLE: Run `feast apply` (${{ env.ENV_ZONE }})
          SLACK_MESSAGE: Feature store has been deployed successfully.
      
      # Run `feast apply`
      - uses: actions/checkout@v2
      - name: Install feast
        run: pip install "feast[aws]=="$FEAST_VERSION
      - name: Run feast apply
        run: cd $ENV_ZONE; feast apply
